/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomFormatDialog: typeof import('./src/components/CustomFormatDialog.vue')['default']
    EncoderConfig: typeof import('./src/components/EncoderConfig.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    FilterConfig: typeof import('./src/components/FilterConfig.vue')['default']
    FormatSelect: typeof import('./src/components/FormatSelect.vue')['default']
  }
}
