// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NInput: typeof import('naive-ui')['NInput']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    Pinyin: typeof import('./src/components/Pinyin.vue')['default']
    Shorten: typeof import('./src/components/Shorten.vue')['default']
    Tool: typeof import('./src/components/Tool.vue')['default']
    Zici: typeof import('./src/components/Zici.vue')['default']
  }
}

export {}
