// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function Success(arg1) {
  window['go']['main']['App']['Success'](arg1);
}

export function ConvDict(arg1, arg2, arg3, arg4) {
  window['go']['main']['App']['ConvDict'](arg1, arg2, arg3, arg4);
}
