// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function Shorten(arg1, arg2) {
  window['go']['main']['App']['Shorten'](arg1, arg2);
}

export function ConvDict(arg1, arg2, arg3, arg4) {
  window['go']['main']['App']['ConvDict'](arg1, arg2, arg3, arg4);
}
