// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function Success(arg1:boolean):void;

export function ConvDict(arg1:string,arg2:string,arg3:string,arg4:boolean):void;
