// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Convert'](arg1, arg2, arg3, arg4);
}

export function Encode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Encode'](arg1, arg2, arg3, arg4);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function Shorten(arg1, arg2) {
  return window['go']['main']['App']['Shorten'](arg1, arg2);
}
