// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:number,arg7:string):Promise<void>;

export function Encode(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SelectFile():Promise<string>;

export function Shorten(arg1:string,arg2:string):Promise<void>;
