// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1:string,arg2:string,arg3:string,arg4:boolean):void;

export function Encode(arg1:string,arg2:string,arg3:string,arg4:boolean):void;

export function SelectFile():Promise<string>;

export function Shorten(arg1:string,arg2:string):void;
